export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CHARACTER_REPOSITORY = 'CHARACTER_REPOSITORY';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const FILE_UPLOAD_SERVICE = 'FILE_UPLOAD_SERVICE';
export const EXTERNAL_API_SERVICE = 'EXTERNAL_API_SERVICE';
