version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: gwan_db
    environment:
      POSTGRES_DB: gwan_vector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pazdedeus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gwan_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gwan_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gwan_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gwan_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:pazdedeus@db:5432/gwan_vector
      REDIS_URL: redis://redis:6379
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    networks:
      - gwan_network
    command: npm run start:dev

  # Frontend App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gwan_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - gwan_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  gwan_network:
    driver: bridge 