version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: gwan_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gwan_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gwan_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gwan_network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: gwan_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - gwan_network
    command: server /data --console-address ":9001"

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gwan_backend
    environment:
      # Database
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      
      # Server
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      
      # Email
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
      # WhatsApp API
      WHATSAPP_API_URL: ${WHATSAPP_API_URL}
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
      
      # Upload
      UPLOAD_PATH: ${UPLOAD_PATH}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # MinIO
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - db
      - redis
      - minio
    networks:
      - gwan_network

  # Frontend App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gwan_frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_ENV: ${REACT_APP_ENV}
      REACT_APP_NAME: ${REACT_APP_NAME}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gwan_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  gwan_network:
    driver: bridge 