version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: gwan-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=https://video.gwan.com.br/api
      - NODE_ENV=production
    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-frontend.rule=Host(`video.gwan.com.br`)"
      - "traefik.http.routers.gwan-frontend.entrypoints=websecure"
      - "traefik.http.routers.gwan-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: gwan-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-backend.rule=Host(`video.gwan.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gwan-backend.entrypoints=websecure"
      - "traefik.http.routers.gwan-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.gwan-backend.middlewares=gwan-backend-stripprefix"
      - "traefik.http.middlewares.gwan-backend-stripprefix.stripprefix.prefixes=/api"

networks:
  gwan:
    external: true 